name: CI - Build, Lint, and Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT
      - name: Checkout repository
        uses: actions/checkout@v4

      # SET UP NODE
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # INSTALL DEPENDENCIES
      - name: Install dependencies
        run: npm install
        working-directory: app

      # LINT NODE CODE
      - name: Run ESLint (code quality check)
        run: |
          npx eslint . || true
        working-directory: app

      # LINT DOCKERFILE
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      # RUN APP & SMOKE TEST
      - name: Start app in background
        working-directory: app
        run: |
          nohup node app.js > server.log 2>&1 &
          echo "Waiting for server to start..."
          sleep 5
          curl -f http://localhost:3000/health || (echo "Health check failed" && cat server.log && exit 1)

      # BUILD DOCKER IMAGE
      - name: Build Docker image
        run: docker build -t devops2-app .
